version: "3"
services:  
  web:
    image: ubuntu:18.04
    deploy:
      replicas: 5
      resources: apache2 - nginx 4 - erminator
        limits:
          cpus: "0.1"
          memory: 50M
    ports: 
      - "80:80"
